### PR TITLE
Add NextJS 13 example

### PR DESCRIPTION
**Pull request by yoDon**
Adding a NextJS TypeScript example and some README steps on using Preline with NextJS 13. 

This might be helpful to folks who had questions in https://github.com/htmlstreamofficial/preline/issues/101 and https://github.com/htmlstreamofficial/preline/issues/83

### CODE REVIEW

**Comment by 2a5A1Ghu1** [comment]
Can confirm that install instructions do work

**Comment by oskarkocol** [comment]
I also confirm that the instructions work.

You're tackling two things here:
* language choice (js vs ts)
* router choice (`app` vs `pages`)

One good improvement could be to highlight that this solution works for the TypeScript **with** `App` Router. Currently available instructions are good for JavaScript with the legacy `Pages` router (and they are still correct).

**Comment by Xt-Man** [comment]
Hi @yoDon , i´m using NextJS 13 with Type Script, but I'm not using app folder, so i don´t have a layout.tsx file
Should i put `<PrelineLoader />` in _app.tsx?

Thx

**Comment by theonlyway** [comment]
Exactly what I was looking for, thanks! Can confirm the doco worked for me on a fresh project using NextJS 13 with App Router and TypeScript

**Comment by felipemaccari** [comment]
that really works for me too, nice job!

**Comment by jahaganiev** [comment]
First of thanks for the input @yoDon - closing this PR, we've added a backlink to your forked repo on framework guides page [here](https://preline.co/docs/frameworks-nextjs.html)

**Pull request closed without merging**
